### YamlMime:ManagedReference
items:
- uid: FarmMaster.Services.IServiceSmtpDomainConfig
  commentId: T:FarmMaster.Services.IServiceSmtpDomainConfig
  id: IServiceSmtpDomainConfig
  parent: FarmMaster.Services
  children:
  - FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
  - FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
  - FarmMaster.Services.IServiceSmtpDomainConfig.VerifyEmail
  langs:
  - csharp
  - vb
  name: IServiceSmtpDomainConfig
  nameWithType: IServiceSmtpDomainConfig
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig
  type: Class
  source:
    remote:
      path: FarmMaster/Services/IServiceSmtpClient.cs
      branch: assignment_script
      repo: https://github.com/Aim-Educational/FarmMaster.git
    id: IServiceSmtpDomainConfig
    path: Services/IServiceSmtpClient.cs
    startLine: 36
  assemblies:
  - FarmMaster
  namespace: FarmMaster.Services
  summary: "\nConfiguration of the various callbacks that certain parts of AimLogin is required to send.\n"
  example: []
  syntax:
    content: public class IServiceSmtpDomainConfig
    content.vb: Public Class IServiceSmtpDomainConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: FarmMaster.Services.IServiceSmtpDomainConfig.VerifyEmail
  commentId: F:FarmMaster.Services.IServiceSmtpDomainConfig.VerifyEmail
  id: VerifyEmail
  parent: FarmMaster.Services.IServiceSmtpDomainConfig
  langs:
  - csharp
  - vb
  name: VerifyEmail
  nameWithType: IServiceSmtpDomainConfig.VerifyEmail
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig.VerifyEmail
  type: Field
  source:
    remote:
      path: FarmMaster/Services/IServiceSmtpClient.cs
      branch: assignment_script
      repo: https://github.com/Aim-Educational/FarmMaster.git
    id: VerifyEmail
    path: Services/IServiceSmtpClient.cs
    startLine: 42
  assemblies:
  - FarmMaster
  namespace: FarmMaster.Services
  summary: "\nNOTE: The verify token for the UserEmail to be verified will be appended onto the end, so the domain should\nend with an incomplete query value, .e.g &quot;?token=&quot;\n"
  example: []
  syntax:
    content: public string VerifyEmail
    return:
      type: System.String
    content.vb: Public VerifyEmail As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
  commentId: P:FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
  id: AnonRequest
  parent: FarmMaster.Services.IServiceSmtpDomainConfig
  langs:
  - csharp
  - vb
  name: AnonRequest
  nameWithType: IServiceSmtpDomainConfig.AnonRequest
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
  type: Property
  source:
    remote:
      path: FarmMaster/Services/IServiceSmtpClient.cs
      branch: assignment_script
      repo: https://github.com/Aim-Educational/FarmMaster.git
    id: AnonRequest
    path: Services/IServiceSmtpClient.cs
    startLine: 47
  assemblies:
  - FarmMaster
  namespace: FarmMaster.Services
  summary: "\nDitto\n"
  example: []
  syntax:
    content: public string AnonRequest { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AnonRequest As String
  overload: FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
  commentId: P:FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
  id: ResetPassword
  parent: FarmMaster.Services.IServiceSmtpDomainConfig
  langs:
  - csharp
  - vb
  name: ResetPassword
  nameWithType: IServiceSmtpDomainConfig.ResetPassword
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
  type: Property
  source:
    remote:
      path: FarmMaster/Services/IServiceSmtpClient.cs
      branch: assignment_script
      repo: https://github.com/Aim-Educational/FarmMaster.git
    id: ResetPassword
    path: Services/IServiceSmtpClient.cs
    startLine: 52
  assemblies:
  - FarmMaster
  namespace: FarmMaster.Services
  summary: "\nDitto\n"
  example: []
  syntax:
    content: public string ResetPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ResetPassword As String
  overload: FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: FarmMaster.Services
  commentId: N:FarmMaster.Services
  name: FarmMaster.Services
  nameWithType: FarmMaster.Services
  fullName: FarmMaster.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest*
  commentId: Overload:FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
  name: AnonRequest
  nameWithType: IServiceSmtpDomainConfig.AnonRequest
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig.AnonRequest
- uid: FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword*
  commentId: Overload:FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
  name: ResetPassword
  nameWithType: IServiceSmtpDomainConfig.ResetPassword
  fullName: FarmMaster.Services.IServiceSmtpDomainConfig.ResetPassword
